config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dashboard
  resources :chat_rooms
  resources :messages
  resources :themes
  resources :admin

  root 'chat_rooms#index'

  get 'chat_rooms_controller/index'
  get '/users', to: 'chat_rooms#index'

  match 'users/:id' => 'users#edit', :via => :update, :as => :admin_update_user
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  authenticate :user do
    mount ActionCable.server => '/cable'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_and_belongs_to_many :themes

  validates :title, presence: true, length: {minimum: 2, maximum: 20}
  validates :description, presence: true, length: {minimum: 5, maximum: 50}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def hours
    created_at.strftime('%H:%M')
  end

  def seconds
    created_at.strftime(':%S')
  end

  def mentioned?
    body.downcase.include?(user.nickname.downcase)
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :chat_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :nickname
  validates :firstname, presence: true, length: {minimum: 2, maximum: 20}
  validates :lastname, presence: true, length: {minimum: 2, maximum: 20}
  validates :nickname, presence: true, length: {minimum: 2, maximum: 20}
  validates :email, presence: true, length: {minimum: 2, maximum: 40}

  def name
    nickname
  end

  def is_admin?
    admin
  end

  def has_profile?
    profile.present?
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :chatrooms

  def chatrooms
    @chat_rooms = ChatRoom.all
    @themes = Theme.all
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
    @chat_rooms = ChatRoom.all
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params) unless current_user.blank?
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def edit
    @chat_room = ChatRoom.find(params[:id])
  end

  def update
    @chat_room = ChatRoom.find(params[:id])

    if @chat_room.update_attributes(chat_room_params)
      redirect_to @chat_room
    else
      render 'edit'
    end
  end

  def destroy
    @chat_room = ChatRoom.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :description, theme_ids: [])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def show
    @message = Message.all.order_by(:body)
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to :back
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :chatrooms

  def chatrooms
    @chat_rooms = ChatRoom.all
    @themes = Theme.all
  end

  private

    def sign_up_params
    params.require(:user).permit(:nickname, :firstname, :lastname, :email, :password, :password_confirmation)
    end

    def account_update_params
    params.require(:user).permit(:nickname, :firstname, :lastname, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!

  def index
    @themes = Theme.all
  end

  def new
    @theme = Theme.new
  end

  def show
    @theme = Theme.find_by(id: params[:id])
    @themes = Theme.all
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      flash[:success] = 'Chat room added!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @theme = Theme.find(params[:id])
  end

  def update
    @theme = Theme.find(params[:id])

    if @theme.update_attributes(theme_params)
      redirect_to @theme
    else
      render 'edit'
    end
  end

  def destroy
    @theme = Theme.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  private

  def theme_params
    params.require(:theme).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
        redirect_to root_url, notice: "User deleted."
    end
  end

  def edit
    @user = User.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="#{image_path("emoji/#{emoji.image_filename}")}" style="vertical-align:middle" width="20" height="20" />)
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.slim
.usermodal
  h1 User database
  p Manage your users here.
  .user-row
    .column.top Nickname
    .column.top First name
    .column.top Last name
    .column.top Admin?
    .column.top Email
    .column.top Actions
  - @users.each do |user|
    .user-row
      .column= user.nickname
      .column= user.firstname
      .column= user.lastname
      .column= user.admin
      .column= user.email
      .column
        =link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } 

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "#{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/_form.html.erb
<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control', id: "chatroom_title" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, autofocus: true, class: 'form-control', id: "chatroom_description" %>
  </div>
  <%= f.collection_check_boxes(:theme_ids, Theme.all, :id, :name) do |b| %>
    <div class="form-group">
      <%= b.check_box(class: "check_box") %> <%= b.object.name %>
    </div>
  <% end %>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/_list.html.slim
= render @chat_rooms

app/views/chat_rooms/_new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/edit.html.erb
<div class="usermodal">
<% if current_user && current_user.is_admin? %>
  <h1>Edit chat room</h1>

  <%= render 'form' %>
<% else %>
  <% controller.redirect_to root_path %>
<% end %>
</div>

app/views/chat_rooms/index.html.slim
.usermodal
  h1 Welcome to TogetherChat!
  p You are currently at the homepage. Please choose a channel to chat with others!
  
  p You can also create channels to organize your chat even more efficient!
  
  br
  p This project is made to learn more about ActionCable.
      

app/views/chat_rooms/new.html.erb
<% if current_user && current_user.is_admin? %>
  <h1>Add chat room</h1>

  <%= form_for @chat_room do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: 'form-control', id: "chatroom_title" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, autofocus: true, class: 'form-control', id: "chatroom_description" %>
    </div>

    <%= f.submit "Add!", class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <% controller.redirect_to root_path %>
<% end %>

app/views/chat_rooms/show.html.erb
<header>
  <div class="channelInfo">
    <h1 class="assignChannel"><%= @chat_room.title %></h1>&nbsp;~&nbsp;
    <h3><%= @chat_room.description %></h3>
  </div>
  <% if current_user.is_admin? %>
    <h4>Admin Tools: <%=link_to "Delete channel",chat_room_path(@chat_room.id), 'data-method' => :delete, :class => "delete", :confirm => "Are you sure ?", id: "delete-chatroom"%>
     <%=link_to "Edit channel",edit_chat_room_path(@chat_room.id), :confirm => "Are you sure ?"%></h4>
  <% end %>

</header>
<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>

<div class="chatinput">
  <%= form_for @message, url: '#', id: 'formSubmit' do |f| %>
    <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
    <div>
        <%= f.text_field :body, class: 'form-control', placeholder: 'Type your message...' %>
    </div>
  <% end %>
</div>

app/views/dashboard/_navigation.html.slim
.list-content
  .application-name
    | TogetherChat
  .channel-tab
    h3 CHANNELS
    ul
      = render @themes
        
          
  .profile-tab
    h3 Profile
    .edit-profile-btn 
      =link_to "Edit", edit_user_registration_path 
    .profile-info-container
      .profile-avatar
        = gravatar_for current_user
      .profile-name
        | @
        = current_user.name 
        .profile-email
          = current_user.email
      .logout
        = link_to destroy_user_session_path, :method => :delete
          img src="http://res.cloudinary.com/unique/image/upload/v1479713991/exit_nfqhkf.png"
    - if current_user.is_admin?
      .admin-tab
        a ADMIN OPTIONS
        .admin-options
          br
          br
          = link_to "Add a theme", new_theme_path
          br
          = link_to "Add a chatroom", new_chat_room_path
          br
          = link_to "View users", admin_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Together</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="flexbox">
      <% if current_user %>
        <%= render 'dashboard/navigation' %>
      <% end %>
      <div class="page-content">
        <%= yield %>
        <div class="popup">
          <div class="notice"><%= notice %></div>
          <div class="alert"><%= alert %></div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.slim
.message
  .avatar
    = gravatar_for message.user
  .message-information
    .author
      = message.user.name
    .timestamp
      = message.hours
    - if message.mentioned?
      .message-body.mentioned
        = message.body
    - else
      .message-body
        = simple_format(message.body).gsub(URI.regexp, '<a href="\0">\0</a>').html_safe

app/views/themes/_form.html.erb
<%= form_for @theme do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/themes/_theme.html.slim
.themename
  = theme.name 
  = link_to "X" , theme_path(theme), 'data-method' => :delete, :class => "delete", confirm:"Are you sure ?" unless !current_user.is_admin?
  
- theme.chat_rooms.each do |room|
  li= link_to "#{room.title}", chat_room_path(room)
  

app/views/themes/new.html.erb
<div class="usermodal">
<% if current_user && current_user.is_admin? %>
  <h1>Add theme</h1>

  <%= render 'form' %>
<% else %>
  <% controller.redirect_to root_path %>
<% end %>
</div>